name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        
    - name: Install Gradle
      run: |
        export GRADLE_VERSION="6.0"
        wget -q "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -P /tmp
        unzip -q -d /opt/gradle "/tmp/gradle-${GRADLE_VERSION}-bin.zip"
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" > gradle/wrapper/gradle-wrapper.properties
        chmod +x /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle
        ln -s /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build
